### ISSUE TITLE
How to install it in Linux 

### ISSUE THREAD

**Issue by arifzeeshan** [jaredallard/notion-app#1]
I have run the script and I got the tar file,how do I install it ?

**Comment by jaredallard** [comment]
Hey @arifzeeshan, sorry I somehow never saw this until now! So, once you have a tarfile you need to extract it to `/opt/notion` and then cp the `notion` shell script to `/usr/bin/notion`

**Comment by arifzeeshan** [comment]
It would be helpful for a lot of person if you update the same in Readme file.
