### ISSUE TITLE
disable auto updater

### ISSUE THREAD

**Issue by shreya-shah** [jaredallard/notion-app#11]
the auto update is not working 
so is it possible to disable the updater?

**Comment by mr-islam** [comment]
Same issue for me, when launching the notion executable from the terminal it lists the auto updater as the source of the error.

I've gone back to using the [notion deb release](https://github.com/davidbailey00/notion-deb-builder)

**Comment by juliapacula** [comment]
I have the same issue, waiting for the fix or help to sort it out. 

I have installed notion-enhancer and fisrt launch of application is working, but after closing the app I cannot open it again.

**Comment by mr-islam** [comment]
I don't know how it's related, but this [fork of this repo](https://github.com/haydn-jones/notion-deb-builder) that creates an `asar` file works fine and works on subsequent relaunches without issue. 

(And @juliapacula I am able to install notion-enhancer successfully!)

EDIT: Sorry, I made a big slip up above, I meant "this fork of the notion-deb repo". Three conversations across 2 apps on the same topic get confusing fast 😅

**Comment by juliapacula** [comment]
@mr-islam How did you install notion-enhancer then? I tried to do the whole proccess, but now I am a bit lost :disappointed: I cloned notion-deb-builder, switched electron-installer-deb to electron-installer-redhat to produce rpm file. But I have no idea where notion-enhancer should come in proccess.

Should I clone notion-enhancer too, switch path (in pkg/helper.js) to look for my directory, where notion-deb-builder built notion before compiling it to rpm package and then try to run notion-enhancer's apply?

**Comment by mr-islam** [comment]
@juliapacula We might be getting off-topic on this repo 😅️

Let's continue this discussion about [notion-enhancer on it's issue here](https://github.com/dragonwocky/notion-enhancer/issues/150#issuecomment-706672100); I ended up outlining all the steps I took maybe someone else can benefit too

**Comment by jaredallard** [comment]
I'm going to consider this out-of-scope for this repo, since we're really meant to just take what notion has an repack it! Sorry :)
