### ISSUE TITLE
Ubuntu install not working

### ISSUE THREAD

**Issue by LucasDondo** [jaredallard/notion-app#13]
(Actually it is ZorinOS Core, not Ubuntu)
I followed the given procedure, so I did:
`sudo apt install 7z pz7ip 7zip p7zip-full dmg2img` > I added some packages given the error below.
`git clone https://github.com/jaredallard/notion-app.git`
`cd notion-app/`
`sudo ./build.sh [--no-compress]` (I also tried `sudo ./build.sh`)
And then, the output is:
`ERROR: 7z not found (pz7ip?)`

**Comment by SebbyBB** [comment]
Similar issues here on Ubuntu (20.04), also had errors (Unable to locate package) for 7z, pz7ip and 7zip but was able to install by cloning into the repo. The build also worked, but no sign of notion-enhancer working when notion is started.

Tried uninstalling notion and reinstalling and no luck. `notion-enhancer check` says that notion-enhancer is already applied.

**Comment by SebbyBB** [comment]
There is another version of notion that is installed differently, try [this link](https://github.com/davidbailey00/notion-linux) and see if that works for you. Not a direct fix of this issue, but it worked for me

**Comment by LucasDondo** [comment]
Yes, I had already tried that one, but as you said, it is not a solution for this issue in this repo. 🤷🏼‍♂️️

**Comment by jaredallard** [comment]
Sounds like `7z` isn't in your `PATH`

**Comment by LucasDondo** [comment]
> Sounds like `7z` isn't in your `PATH`

Should that be done automatically? Or manually (in which case, the command could be added to the installation instructions)?
