### ISSUE TITLE
The system tray icon does not appear notion-app

### ISSUE THREAD

**Issue by Emporioe** [jaredallard/notion-app#14]
System: Arch
desktop: KDE 

The system tray icon does not appear with notion-app. This happened when I let notion start with the system and latte does not recognize it anymore.

![Screenshot_20210909_134357](https://user-images.githubusercontent.com/69167077/132744600-886a8828-eca8-4696-8eea-ee935abeae35.png)

**Comment by jaredallard** [comment]
@Emporioe I was unable to reproduce this. Is this still ocurring?
