### ISSUE TITLE
Is it possible to configure spell check to validate multiple languages like we do in chrome?

### ISSUE THREAD

**Issue by brunobmello25** [jaredallard/notion-app#15]
My OS is in enlish but I'm not a native english speaker, so sometimes I write stuff in other languages as well (brazilian portuguese).

In chrome I can configure spell checking to validate both american english and brazilian portuguese and it works fine. Is it possible to do the same with this package? Having my whole note underlined with red lines because I'm writing in portuguese is kind of a bummer

**Comment by jaredallard** [comment]
I believe so, but I think this would be based on electron (which I don't now much about. I'll mark this as an enhancement as I'd also like it, so I work with Japanese a lot!
