### ISSUE TITLE
AUR pkg

### ISSUE THREAD

**Issue by pat-s** [jaredallard/notion-app#2]
I just built an AUR package from your sources, adapting your `PKGBUILD`. Would you mind if I push it to AUR? Ofc mentioning you in the PKGBUILD.

I use the community build of `electron` to build it and put most of the `build.sh` and `config.sh` parts directly into the PKGBUILD.

**Comment by pat-s** [comment]
Now available here: https://aur.archlinux.org/packages/notion-app/

You're welcome to become a co-maintainer.

**Comment by jaredallard** [comment]
@pat-s Thanks. No idea how I missed this until now!

You're welcome to maintain it, I might take up co-maintainership later but I don't see that happening anytime soon w/ my free-time being very... constricted as is.
