### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by svechinsky** [jaredallard/notion-app#4]
Just went through the install process, very cool, thanks.
Noticed I was missing some dependencies, might want to add them to the readme:
7zip (p7zip-full)
dmg2img

**Comment by avinashkanaujiya** [comment]
i have gone throught the install process, and i have a .img file now, but how to use it.

**Comment by hlzl** [comment]
> i have gone throught the install process, and i have a .img file now, but how to use it.

Check out #1

**Comment by jaredallard** [comment]
Sorry about this, turns out I was unsubscribed from notifications for this repo which is why I've been real bad about replying.

I'll add those, or accept a PR to add them @svechinsky!
